### ISSUE TITLE
需要解决单元测试在 CI 无法通过

### ISSUE THREAD

**Issue by kun-song** [satansk/Summer#1]
本地跑没问题，连接的是本地的 MongoDB，在 CI 上没有数据库，会失败，应该在 Repository 层打桩。

**Comment by satansk** [comment]
使用 SpringBoot Test 进行单元测试:
1. Controller 层使用 Mockito + MockMvc 处理。
2. Service 层使用 Mockito。
3. Repository 层使用内存嵌入式 MongoDB 测试，速度快、不依赖实际环境。
